apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: springboot-deployment
spec:
  selector:
    matchLabels:
      app: springboot
  replicas: 2 # tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  minReadySeconds: 5
  revisionHistoryLimit: 10
  
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot
        image: rajachalla76/spring-boot-mongo
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  labels:
    app: springboot
spec:
  selector:
    app: springboot
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31200
---
# Mongo host path rc
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  selector:
    matchLabels:
      name: mongo
  replicas: 1 # tells deployment to run 2 pods matching the template
  
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        hostPath:
         path: /tmp/dbbackup
---
# Mongo Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo
